### ISSUE TITLE
CSI operator on Openshift in restricted network

### ISSUE THREAD

**Issue by fideltak** [hpe-storage/co-deployments#195]
Im trying to install HPE CSI operator into my Openshift which is in **NO internet environment**.
I could bring CSI operator to my Openshift by regarding to this [instructions](https://docs.openshift.com/container-platform/4.3/operators/olm-restricted-networks.html).
After creating HPE CSI Driver, Im facing image pulling error like below.

```
    Image:         quay.io/k8scsi/csi-provisioner:v1.5.0
    Image ID:      
      Reason:       ErrImagePull
    Image:         quay.io/k8scsi/csi-attacher:v2.1.1
    Image ID:      
      Reason:       ErrImagePull
    Image:         quay.io/k8scsi/csi-resizer:v0.4.0
    Image ID:      
      Reason:       ErrImagePull
    Image:         hpestorage/csi-driver:v1.3.0
    Image ID:      
      Reason:       ErrImagePull
    Image:         quay.io/hpestorage/volume-mutator:v1.0.0
    Image ID:      
      Reason:       ErrImagePull
    Image:         quay.io/hpestorage/csi-extensions:v1.0.0

etc...
```
I know this problem is caused by my network does not allow internet access. So it seems operator could not execute helm.
How can I use HPE CSI operator in restricted network like my environment?
Do you have any ideas?

[Version]
RedHat Openshift: 4.3
HPE CSI Operator: 1.3.0

**Comment by datamattsson** [comment]
There's no way to run the CSI Operator on air-gapped networks with version v1.3.0. We are introducing a `registryPrefix` parameter in v1.4.0 (PR: #188), that will allow you to push the images to your internal registry and have the worker nodes pull from there.

While not supported by Red Hat (and not really tested by us either to be frank), you can deploy the driver from the object definitions described here: https://scod.hpedev.io/csi_driver/deployment.html#advanced_install (OpenShift 4.3 uses Kubernetes 1.16). Just replace the `image: ` tags in the YAML files pointing to your internal registry.

**Comment by fideltak** [comment]
@datamattsson 
Thank you for your advice. Im going to wait for v1.4.0.
