### ISSUE TITLE
Use digests instead of tags

### ISSUE THREAD

**Issue by ondrejlinha** [hpe-storage/co-deployments#231]
Hello, 

Would it be possible to start using image SHA digests instead of tags since tags for 'ImageContentSourcePolicy' resources are no longer supported by Red Hat[1]?

Using tags makes the whole operator unusable in OpenShift 4 disconnected environments[2][3].

If you need I can prepare a PR for the next release.

[1] https://access.redhat.com/solutions/4817401
[2] https://github.com/openshift/api/issues/636
[3] https://github.com/openshift/okd/issues/226

Cheers,
Ondrej

**Comment by datamattsson** [comment]
> Using tags makes the whole operator unusable in OpenShift 4 disconnected environments[2][3].

We added a "registry" parameter to allow pulling images from an internal registry for air-gapped installs.

Sifting through your provided links (thanks!) I can see that "registry" won't be very helpful in those scenarios. Let me bring this up with product management.

**Comment by datamattsson** [comment]
We've switched to pulling by digest. Can you please confirm with v2.4.2 of the Operator?
