### ISSUE TITLE
ClusterRole hpe-csi-driver-role should not have a namespace

### ISSUE THREAD

**Issue by jellehelsen** [hpe-storage/co-deployments#282]
The hpe-csi-driver-role ClusterRole currently has a namespace declared. See https://github.com/hpe-storage/co-deployments/blob/a9f11c577ea9d8207b8b6b74f3da8f69058e711e/helm/charts/hpe-csi-driver/templates/hpe-csi-rbac.yaml#L484-L488

When deploying the helm chart with Anthos ConfigSync this results in an error: `cluster-scoped resources MUST NOT declare metadata.namespace` .

**Comment by datamattsson** [comment]
@jellehelsen thanks for reporting this. This will be fixed in the Helm chart which will be part of the next release. There might be a another beta/pre-release chart pushed in between now and then.

In the meantime, you can either fork and build the chart yourself or deploy using the YAML manifests.
