### ISSUE TITLE
consistency in image registry for deployment manifests

### ISSUE THREAD

**Issue by jonasgovaerts** [hpe-storage/co-deployments#331]
When we are deploying the operator with the provided helm chart with a custom registry in the values file
the deployment fails with some pods stuck in ImagePullBackOff state

Our deployment is using a harbor registry with both quay.io and registry.k8s.io configured as proxy cache projects

Is it normal behaviour that images are being pulled from two different upstream registries?
Wouldn't it be better to have consistency?

registry.k8s.io/sig-storage/csi-provisioner:v3.3.0
registry.k8s.io/sig-storage/csi-attacher:v3.5.1
registry.k8s.io/sig-storage/csi-snapshotter:v5.0.1
registry.k8s.io/sig-storage/csi-resizer:v1.6.0
quay.io/hpestorage/csi-driver:v2.3.0
quay.io/hpestorage/volume-mutator:v1.3.3
quay.io/hpestorage/volume-group-snapshotter:v1.0.3
quay.io/hpestorage/volume-group-provisioner:v1.0.3
quay.io/hpestorage/csi-extensions:v1.2.4

**Comment by datamattsson** [comment]
We use upstream SIG Storage images pulled from their official sources, besides the official HPE images on Quay. It's not too uncommon using different registry sources. Instructions on how to pull all our source images into your private registry is available here: https://scod.hpedev.io/csi_driver/deployment.html#helm_for_air-gapped_environments

**Comment by datamattsson** [comment]
I would also hold on deploying the 2.3.0 Operator as we've not yet officially released that one. Follow the PR here: https://github.com/k8s-operatorhub/community-operators/pull/2463
